2Abendsegler/GClh

gc_little_helper_II.user.js
Hallo,
hier der Merge Request für das Feature #34 Abspeichern von benutzerdefinierten Suchen.
Das Feature ist über die Settings deaktivierbar - Standard ist an. 
Das Integrieren von meinen Stand-alone Skript in GClh war sagenhaft einfach.
Das Feature bezieht sich auf die Seite: https://www.geocaching.com/play/search - So fern schon gespeicherte Suchen vorhanden sind erscheint dort der Button "Manage Filter Sets" bzw. wenn eine Suche durchgeführt worden ist (Ergebnisliste)
Features
- Suchen aufrufen
- Suche speicern
- Umbenennen
- Editieren/Update (aktuelle Suche übernehmen)
- Löschen
Gerne mal das Feature ausprobieren
Gruß
CachingFoX
=> Abspeichern von benutzerdefinierten Suche

gc_little_helper_II.user.js
Issue 181 implementation completed, option 'Link to bigger images in listing' in config
=> #Issue 181

gc_little_helper_II.user.js
Ich habe ergänzt, dass die beiden Checkboxen über dem Submit-Button im Formular beim bearbeiten eines Geocaches automatisch gesetzt werden. Allerdings gibt es keine Option in der Konfiguration dieses Feature zu disablen
=> Fix #230: Auto check checkboxes on hide report

gc_little_helper_II.user.js
Ich habe in der Mapansicht in dem Seitenmenü zwei Button hinzugefügt, mit denen man auf einmal alle Cachearten ein- bzw. ausblenden kann.
So kann man bei großen Zoomstufen auf der Karte auch noch etwas von den Beschriftungen erkennen.
Eventuell sollte man die Links noch Stylen und/oder Bilder hinzufügen.
=> Added Buttons for Show/Hide all Caches on the Map

gc_little_helper_II.user.js
Ich habe über die BRouter Funktion geschaut und ein paar Anpassungen für das CSS gemacht. Ansonsten finde ich die Funktion toll. Das kannte ich bisher nicht 😉 (fixes #425). Weiterhin gibt es jetzt Links für BRouter und Flopps in der Sidebar und man kann beides (separat) in der Konfig aus- bzw. einschalten (Im Konfig Bereich unter Listing) (fixes #294, fixes #308).
Zu #297 : der Link zu Flopps ist nun in der Sidebar, auch wenn es keine zusätzlichen Waypoints gibt (fixes #297).
=> Feature BRouter, Links in Sidebar for BRouter and Flopps, Config Value to turn both options off

gc_little_helper_II.user.js
GClh übernimmt die Access Tokens von Dropbox auch wenn es ein anderes Script angefordert hatte. Dies sollte es beheben.
=> Dropbox Token überprüfen ob es für GClh ist

gc_little_helper_II.user.js
Did you ever browse the calendar? Year or two back? GC provides scrolling by only one month. Very slow browsing.
This new feature adds two selections to the calendar. You can quickly select a year or a month.
Here is result:
=>  Added a new function: active select date into geocaches and travelbugs calendar

gc_little_helper_II.user.js
Please review. 
The elevation of waypoints with unknown coordinates are now marked with "n/a"
=> fix #670: check if the coordinates of a waypoint is unknown

gc_little_helper_II.user.js
(Naja, vermutlich gings doch über den alten PR. Hier siehts ja genauso kunterbunt aus. Bei genauerer Betrachtung wurden zahlreiche blanks am ende der Zeile entfernt.)
Wie erwartet kann Chrome nicht mit "overflow: -moz-hidden-unscrollable;"
Bevor ich mir einen abbreche, hab ich die Änderungen nur für FF implementiert. :)
1. Gehe zu https://www.geocaching.com/map/default.aspx?lat=42.53325&lng=1.580833#?ll=42.56312,1.58927&z=18
2. Auf Cache klicken
=> Line break for cache title and owner in additional popup on map #768

data/config_standard.txt
=> Show both tabs "Active Pocket Queries" and "Pocket Queries Ready for Download" together of one page. #835

gc_little_helper_II.user.js
Getestet für mögliche Kombinationen der Parameter
- Hide Personal Cache Notes if empty
- Hide Personal Cache Notes completely
Getestet wenn F2 Key abgeschaltet.
Helptext wurde ergänzt.
=> Save Personal Cache Note in cache listing with F2 key #907

gc_little_helper_II.user.js
Getestet mit eigenen BML, mit shared BML und mit public BML.
Das kommt nur vor wenn man keine Home Koordinaten im GClh hat, also so gut wie nie. Merge es und gut ist. :)
=> Error on shared bookmark lists #970: Upload js

gc_little_helper_II.user.js
Thunderforest will wohl Geld haben, daher ist die OpenCycleMap bei Flopp und Brouter nicht mehr auswählbar
=> map update Flopp & Brouter - no more OpenCycleMap

gc_little_helper_II.user.js
#1115 
Ich habe die variable für den config nicht ans Ende gepackt, da ich finde, dass sie thematische zu den anderen passt und es verwirrend wäre, wenn sie unten stehen würde.
=> Hide DNF smileys by default in browse map (old map)  #1115

gc_little_helper_II.user.js
Maximum distance between Mystery listing and final coordinates is 3200m, not 3000m as currently stated in the script. The info is used to draw the circle on Flopps map.
"Final coordinates must be less than 2 miles (3.2 km) from the posted coordinates." https://www.geocaching.com/play/guidelines
=> Correct Mystery radius for Flopp

gc_little_helper_II.user.js
Das Script stürzte bei Ownernamen mit Sonderzeichen am Anfang des Namens ab. Es liegt an der ID-Abfrage in `setLinkToOwner()`
Beispiel: 
https://www.geocaching.com/play/map?gc=GC7ZZYH
#1317
=> Problems-with-some-special-characters-at-ownerlink

gc_little_helper_II.user.js
#1491
Die Einstellungen im  Config gelten nach wie vor identisch:
In einer eigenen Statistic (Statistic oder eigenes Profil) und in einer fremden Statistic wird die Matrix wenn gewünscht kalkuliert:
In einer eigenen Statistic (Statistic oder eigenes Profil) werden alle Links und alle title der Kombinationen in der Matrix erweitert um "map" oder "list" und um einen Radius, wenn gewünscht. Die Ausführung der Liste wird gegebenenfalls in die neue Karte weitergeleitet:
=> Rebuild D/T Matrix functionality together with implemented enhancements of GS.

gc_little_helper_II.user.js
#1542 
Leider funktioniert das prüfen auf `$('#gc-header')[0]` nicht zuverlässig. Manchmal läuft das Skript schneller als der Header von GC geladen wird. 
Da `is_page('hide_cache')` schon vergeben ist und mehrere Seiten anspricht, auf denen es dann zu Fehlern kommt, habe ich die URL mit `.match()` verwendet.
=> [Hide Cache] Header

gc_little_helper_II.user.js
Notice scrolling, only if we are on the first part of the lists of the caches.
#1538
=> New map, scroll to last position

gc_little_helper_II.user.js
- [Old Map] GClh Error: Copy to clipboard: anker_element.parentNode is undefined.
Dazu kommt es wenn man zu schnell die Zusatzdaten anfordert, man also zu schnell auf die Cache Icons klickt.
---
- [Old Map] Additional data: Do not cut own favorite Icon.
---
- [Global] Menus aligned evenly.
- [Souvenirs] Show buttons are not always displayed because the souvenirs dashboard is not there yet.
---
- [Global] Faster CSS loading for deactivate GS header.
- [Listing] Display listing images not over the maximum available width.
- [Events] GClh TypeError with click to dynamical copy to clipboard entries: Events have no favorite score. (capoaira)
- [Listing print] Process additional features like other coordinates, decrypt hints ... again on print page.
- [Listing print] Display listing images on …
=> Prepare v0.10.21

data/gclh_defi.js, gc_little_helper_II.user.js
Update Geonames service to more secure https protocol.
Recently I ran into the issue that the elevation in cache listings could not be retrieved anymore by Geonames service in Firefox.
Reason was the Firefox setting "Nur-HTTPS-Modus in allen Fenstern aktivieren" in "Datenschutz und Sicherheit".
This setting prevents proper fetching of data from [http://api.geonames.org](http://api.geonames.org) since the certificate isn't trustworthy.
A switch to [https://secure.geonames.org](https://secure.geonames.org) solves the issue.
=> [Cache Listing] Switch Geonames service to more secure https

data/init.js, gc_little_helper_II.user.js
#1857
@capoaira 
Ich habe die Anpassungen etwas anders realisiert, weil
- mit dem Namen des Services, also hier 'Geonames-Elevation', einiges verbunden ist. Deshalb müssen wir auch für den Fallback diesen Namen verwenden.
- in der Service Auswahl im Config der Fallback nicht wählbar sein darf.
- der Fallback unmittelbar nach dem Original laufen sollte und nicht als letztes.
Getestet habe ich durch Manipulation von `function addElevationToWaypoints_GeonamesElevation`. Dort habe ich die Secure url als Service unavailable deklariert. Die Secure url lief also auf Fehler und anschließend lief der Fallback. Im Fehlerfall wird nun auch die url mit in die Console geschrieben damit wir die beiden Services unterscheiden können. 
Das sollte also passen. 😬
=> Geonames fallback (2)

gc_little_helper_II.user.js
#1884 
Die Änderung von `gcCode = this.trim().toUpperCase().substring(2);` zu `let gcCode = this.trim().toUpperCase().substring(2);`
Hat nichts mit dem Feature zu tun. Mir ist nur aufgefallen, dass ich dort die Deklaration vergessen habe.
=> Automatic opt out to the old log form

gc_little_helper_II.user.js
Upload js
#1929
Die erste Änderung betrifft die erste Zeile mit den Buttons, so wie im Issue beschrieben.
---
Die zweite Änderung betrifft zusätzlich die Größe der blauen BML Labels. Die habe ich auch wieder kleiner gemacht.
---
Die dritte Änderung betrifft zusätzlich die Farbe des Back Buttons wenn man im in einem Cache aus einer BML ist. Das ist ein Fehler von GS. Fehler ist dort gemeldet, scheint aber nicht zu interessieren.
To reproduce:
1. Button "My Lists" wählen
2. Eine BML wählen
3. Einen Cache aus der BML wählen
4. Back Button ist weiß und kaum sichtbar.
=> [Search Map] The first line of buttons in sidebar is again bigger then necessary in compact layout.

gc_little_helper_II.user.js
Upload js
#1926
---
@capoaira
Bitte schau kurz drüber. Wenns passt kannst du gerne mergen.
Der Menüeintrag war nicht nur bei fremden, sondern auch bei eigenen Bookmarklisten nicht wählbar.
Nach einer entsprechenden Änderung funktionierte das Öffnen der Tabs nicht. Hier war auch noch eine Änderung notwendig.
=> Open caches in new tab in BML

gc_little_helper_II.user.js
#2045 
Ich habe mich entschlossen die Sprache einfach zu entfernen, dadurch nutzt google die Systemeinstellung.
=> Set language in Driving Directions links for the cache coordinates and the waypoints

data/config_standard.txt, gc_little_helper_II.user.js
#2089 
Ich denke, ich habe alle Logtypen erwischt. Announcement kann ich nicht testen, da ich gerade kein Event habe.
Zudem: Die Uhrzeit wird jetzt immer angezeigt und nicht nur bei hover.
=> [Drafts] Log Type Icons

gc_little_helper_II.user.js
The "Hillshadow" service is no longer available. We have removed the feature. We'll keep an eye on it, maybe the service will be reactivated, then we'll reinstall it.
(The adjustments in the script are marked with "Issue 2016".)
#2016
=> [Browse Map] Map overlay "Hillshadow" doesn't work.

data/main.css
Verhindern, dass im Config grüne Zeichen in select Feldern auftauchen, wenn man mit der Maus übers Feld geht. Passiert beispielsweise wenn Config aus neuem Log Formular aufgerufen wird. Beispielfeld "Set default language".
=> [Config] Green signs in config fields.

gc_little_helper_II.user.js
#2183
Ich habe alle Aufrufe zu `gclh_build_vipvup` und `gclh_build_vipvupmail` geprüft.
In zwei Fällen fehlte eine Abfrage ob VIP aktiv ist:
- Cache Zusatzdaten auf Search Map 
Neue Zeile:
`if (!settings_show_vip_list) return;`
- Cache Zusatzdaten auf Browse Map
Neue Zeilen:
`if (settings_show_vip_list) {`
`}`
Nur die beiden Zeilen wurden hier hinzugefügt. Wird etwas dubios angezeigt.
@capoaira 
Kannst du bitte drüber schauen.
=> gclh_build_vipvupmail run into issues if settings_show_vip_list is off

data/config_standard.txt, gc_little_helper_II.user.js
Bei [Settings -> Draft](https://www.geocaching.com/my/#GClhShowConfig#a#settings_drafts_go_automatic_back) sind die beiden Draft relevanten Parameter zu finden.
Bei [Settings -> Log](https://www.geocaching.com/my/#GClhShowConfig#a#settings_drafts_go_automatic_backX0) sind die beiden Draft relevanten Parameter und der nicht Draft relevante Parameter zu finden.
@capoaira 
Moin,
kannst du bitte bei Gelegenheit die automatische Weiterleitung testen?
Danke. 😊
#2208
=> Automatic view posted log after logging

gc_little_helper_II.user.js
=> Checkboxes in cache list of search map are no longer one below the other.

gc_little_helper_II.user.js
- fix count drafts after uploading or deletig #2215 
- fix Cachetype not show if Cache ist Archived/Disabled (Zeile 6442)
Der Fehler, weshalb das Laden nicht aufgehört hat, ist, dass noch die alte statt die neue Anzahl von Drafts genutzt wurde. Das zu beheben hat aber nicht ganz geholfen, weil der `MutationObserver` rumgezickt hat.
Beim Test ist mir aufgefallen, dass bei archivierten Cache der Cachetyp nicht angezeigt wird, das wird durch Zeile 6442 behoben
=> Fix count drafts after uploading or deletig

gc_little_helper_II.user.js
Mir ist gerade beim Testen von #2229 aufgefallen, dass die neuen `label` beim PQ-Splitter nicht anklickbar sind.
Kleine Ergänzung zu #2207
=> PQ-Splitter clickable label

gc_little_helper_II.user.js
This PR adds a functionality to show in cache listings who gave a favorite:
- new button "Show who favorited"
- can be activated/deactivated in settings (active by default)
- deactivate button once it has been pressed (no need to fetch the info again)
- deactivate button for events (no fav points) and caches with 0 favorites
- blue heart icon added to corresponding logs
- new filter link for favorite logs
- restrict function to caches with 500 favorites or less (otherwise waiting time and data load both get too high)
Solves #1054, related to #1454.
=> [Cache listing] Show who gave a favorite in cache listings

gc_little_helper_II.user.js
This PR fixes the map layer sort on Browse map in Chrome and closes #2259.
Reason for the issue is that Chrome handles the order of keys in `for..in` loops differently than Firefox.
Solution is to extract the keys first, sort them and perform a `for` loop over the sorted key array. 
As a consequence sorting now has to be handled inside the injected script function `window["GCLittleHelper_MapLayerHelper"]` rather than outside.
=> [Browse Map] Sorting of map layers doesn't work in Chrome

gc_little_helper_II.user.js
- Fix inactive dynamic log load on cache listings after reset button has been pressed
- TODO comment for another (possible) bug added
Fixes #2252.
=> [Cache Listing] After pressing the reset button, dynamic reloading of logs no longer works.

gc_little_helper_II.user.js
=> Prevent the user area in the header from moving to the left and the play menu from disappear on narrow screens.

gc_little_helper_II.user.js
- optional button to switch cache display between original and corrected coordinates; active by default
- button press toggles between corrected and posted coordinates
- current toggle status is preserved
- works for both, GS and GCLH layer control
Closes #2274.
=> [Search Map] Show found caches at corrected coordinates

README.md, docu/faq.md
- Supported Browser nicht mehr zum Bild verlinken weil das ziemlich häufig angewählt wird.
- Installation tips umbenennen.
- Change Geoclub link.
=> Rework readme, installation tips, FAQ

gc_little_helper_II.user.js
When switching back from corrected to original coordinates, the last selected cache marker jumps to corrected position when it gets selected as first cache. The marker should remain at original position.
Steps to reproduce:
1. Enable show at corrected coordinates
2. Select a cache and notice that the cache marker remains at corrected position
3. Switch to show at original coordinates
4. Select the very same cache and notice that the cache marker jumps to corrected position where it shouldn't
=> [Search Map] Corrected coordinates bug fix

gc_little_helper_II.user.js
Error when parameter `settings_show_vip_list` is set to false.
Now the functionality is independent of vip list functionality.
Closes #2293.
=> [Cache Listing] Bugfix for show who gave cache a favorite

gc_little_helper_II.user.js
The banner removal function was based on color. This was not very stable, for example when using the Dark Reader add-on the color is a shade shifted. Additionally, when automatically hiding blue bars, the user may lose some information (for example, the t-shirt contest that ended today - a virtual cache search on the world map).
So I rewrote the function and based it on the content (checksum of the text content). The user now has a button to hide the banner. The information is stored in the settings and if the user doesn't want to, they won't see the specific banner anymore.
=> [Global] Rewrite the function for remove a blue banner - activate [X] button for user interaction

gc_little_helper_II.user.js
Do not save DB auth token in DB.
=> [Sync] Dropbox authentication keeps getting lost

gc_little_helper_II.user.js
#2418
Bei Events wird nach dem Event Datum von GS automatisch der Logtype "Attended" gesetzt, sofern ein "Attended" noch nicht vorhanden ist. Das Log Datum steht dann auf dem aktuellen Datum und nicht auf dem Event Datum, was richtig wäre. Das Log Datum ist nicht eingabebereit. Unsere Default Einstellung `settings_default_logtype_event` zieht für diesen Fall nie. Der Fehler tritt auch ohne den GClh auf. Es handelt sich hier also um einen Bug auf der Webseite, der aber wohl kaum noch berichtigt wird.
To Reproduce:
1. Parameter [Use old-fashioned log form to log non drafts related logs](https://www.geocaching.com/my/#GClhShowConfig#a#settings_logs_old_fashioned) aktivieren
2. [Event](https://coord.info/GCADYGQ) aufrufen
3. Klick auf "Log your visit"  
---
Vor der Anpassung:
Das Event …
=> Log date not changeable for passed events in old log form

gc_little_helper_II.user.js
=> [Log Form] Log templates and save last log text.

gc_little_helper_II.user.js
#2424 
@2Abendsegler Das wäre meine Lösung. Ich finde die nicht sonderlich schön, daher verstehe ich, wenn du das nicht mergen möchtest.
Vielleicht findest du ja einen Weg, den Logtypen direkt im Logform anzupassen.
=> [Log Form] Default Log Types

gc_little_helper_II.user.js
fixes #2455
@2Abendsegler So, das ist mein aktueller Stand, Templates funktionieren so weit.
Bei der Signatur gibt 2 Bugs:
1. Wenn `.lt-mirror__canvas` nicht existiert, verschwindet die Signatur
2. Wenn es existiert, wird die Signatur zwar erneut eingefügt, aber das Logdatum wird nicht übernommen.
Was noch auf meiner ToDo List steht:
- Für die Signatur teste ich nur auf ein leeres Feld, hier muss noch mit Drafts getestet werden.
Ich brauche jetzt aber erstmal eine kleine Pause.... Bin mir nicht sicher, ob ich heute noch fertig werde.
=> keep signature

gc_little_helper_II.user.js
Das ist Vorschlag 2. aus PR #2454.
> Es wäre schön, wenn man Notification mit demselben Namen gleichzeitig (de)aktivieren könnte. (z.B. mit Rechtsklick, so wie man auch bei den PQs mehrere gleichzeitig (de)aktivieren kann)
=> [Notification] Right mouse click to enable, disable all notifications with same name.

gc_little_helper_II.user.js
close #2506
Ausblenden von gesperrten bzw. eigenen TBs aus der Liste der TBs.
Es gibt zwei neue Parameter mit denen die gesperrten bzw. die eigenen TBs aus der Liste der TBs ausgeblendet werden können.
<a href="https://www.geocaching.com/my/#GClhShowConfig#a#settings_hide_locked_tbs_log_form" title="Link to your GClh II Config">Settings -> Log:</a>
<a href="https://www.geocaching.com/my/#GClhShowConfig#a#settings_hide_own_tbs_log_form" title="Link to your GClh II Config">Settings -> Log:</a>
Bei den Autovisits werden ausgeblendete TBs nun nicht mehr verarbeitet.
Der Edit Button auf der View Log Seite führt nun bei Cache Logs nicht mehr zu einem Austausch des Seiteninhaltes, sondern zum echten Aufruf der Edit Webseite. Das ist notwendig, weil ansonsten die zusätzlichen Informationen zu den …
=> [Log Form] Hide own or locked trackables.

gc_little_helper_II.user.js
The "Copy Logtext to clipboard" icon is no longer supported for trackable logs.
The icon is not always available for trackable logs.
Background: After adding a trackable log and after changing a trackable log, you will automatically be taken to the View Log page. The View Log page is not accessed, only the page content is exchanged. Therefore the logtext is not available on the View Log page.
Clarify the following issues:
- [Log View] "Copy Logtext to clipboard" icon not available after post a TB log. #2513 
- [Log Edit, Log View] "Copy Logtext to clipboard" icon does not contain the changed TB logtext after an update. #2523
Further information are in pull request #2522
---
close #2513
close #2523
=> [Log View] "Copy Logtext to clipboard" icon is no longer supported for trackable logs.

gc_little_helper_II.user.js
This PR eliminates the need of reloading the log page when setting default logtypes.
The code now makes use of React properties of the log type selection.
Related to #2541.
=> [Log Form] Setting default logtypes without page reload

gc_little_helper_II.user.js
On page load a specified URL zoom parameter is ignored and zoom level is set to 14. 
This happens e.g. on mapped matrix searches [(https://www.geocaching.com/my/statistics.aspx#DifficultyTerrainCaches)](https://www.geocaching.com/my/statistics.aspx#DifficultyTerrainCaches), calling the search map from the browse map [(https://www.geocaching.com/play/map?lat=52.52457705042609&lng=13.410186767578123&zoom=16)](https://www.geocaching.com/play/map?lat=52.52457705042609&lng=13.410186767578123&zoom=16) or calling a stored search from a bookmark.
This PR preserves a specified URL zoom parameter on page load.
=> [Search Map] Preserve a specified URL zoom parameter on page load

gc_little_helper_II.user.js
#2107
#2567
Außerdem werden einige abgefangene Fehler, die bisher per `console.log` ausgegeben wurden nun auch per `console.error` ausgegeben.
=> [Cache Listing / Search Map / Browse Map] Geoname elevation errors are no longer displayed in the page header.

data/main.css, gc_little_helper_II.user.js
Only search page is affected. All other pages checked, also the other tech migration pages.
=> [Search] Submenu is no longer aligned correctly.

gc_little_helper_II.user.js
Link was changed from `play/search` to `play/results`. Now the results link is parsed by the regex.
=> fix(Public Profile): old cache type links

gc_little_helper_II.user.js
The link to the cache was not built for Block Parties.
=> fix(Search Map) Link in cache details for caches with cache type "Geocaching HQ Block Party" missing

data/config_standard.txt, gc_little_helper_II.user.js
close #2488
**_[Log Form, Log View] Link to Drafts page is missing (after sending a draft related log, automatic view log)_**
---
close #2490 
**_Additional:  [Log Edit, Log View] After edit a log, go back to log view._** 
Diese Funktionalität ist bereits vorhanden. Wenn man den Parameter [After sending or edit a non draft related cache log, automatic view log](https://www.geocaching.com/my/#GClhShowConfig#a#settings_after_new_logging_view_log) aktiviert, wird auch nach dem Edit eines Cache Logs identisch wie bei einem neuen Log vom Cache Listing zum View Log weitergeleitet.
Ich habe entsprechend die Bezeichnungen und die Hilfetexte der "After sending"-Parameter angepasst. Im Changelog sollten wir darauf hinweisen, dass nach dem Edit eines Cache Logs derart verfahren wird und das es kein …
=> [Log Form, Log View] Link to Drafts page is missing (after sending a draft related log, automatic view log)

gc_little_helper_II.user.js
Implements #2662.
The code for drawing the chart is embedded in the page and therefore redrawing the chart with modified y-scale is straightforward:
- get script from page
- modify y-scale
- redraw chart
For specifying a custom scale, a new user setting `settings_finds_per_month_statistic` has been added.
=> [Statistic] Own scale of graphical monthly found statistics

README.md, docu/changelog.md, docu/changelog_before.md, docu/overview_screenshots.md, docu/tips_installation.md
Some badge logic for `shields.io` has changed. Version and count of installations is no longer working.
=> [GitHub, Badge] Version and count of installations is no longer working.

gc_little_helper_II.user.js
Eigentlich wollte ich die Entwicklung bereits abbrechen, weil der Serien Name für den fraglichen TB "TB9916F" wieder angezeigt wird. Bei genauerem Hinsehen werden aber bei einigen TBs bzw. Coins keine Serien Namen ausgegeben. Tatsächlich wird "alt" bei einigen TBs mal geliefert und mal nicht. Das lässt sich bei folgenden TBs beobachten und das obwohl der Serien Name im Seiten Title vorhanden ist: 
https://coord.info/TB2V8GE
https://coord.info/TB9N38M
https://coord.info/TBA0Y0Q
https://coord.info/TB6WX9Z
Falls "alt" vorhanden ist wird der Serien Name nun von dort genommen, ansonsten wird er aus dem Seiten Title extrahiert.  
---
close #2678
=> [TB Listing] The serial name has no longer been displayed for a travel bug or geocoin.

gc_little_helper_II.user.js
Favoriten Icon verschwindet fast gänzlich hinter dem Found Icon und sitzt auch auf der falschen Seite des Found Icons. Das ist allerdings nicht immer der Fall. Scheinbar nur beim ersten Aufruf des Dashboards. Es werden unsere CSS Styles durch Webseiten eigene überschrieben. Das hängt wohl mit dem Zeitpunkt zusammen, wann die CSS Styles gesetzt werden.
alt:
neu:
=> Dashboard] Favorites icon almost completely disappears behind the found icon.

gc_little_helper_II.user.js
Found some time and had a look into the search map issues after the tech update from GS.
Some of them are fixed with this PR:
1. map selection
2. default filters
3. relocate browse map button
4. hide sidebar
5. display found caches at corrected coordinates
Since some fixes depend on others it was easier to package all in one PR.
Nevertheless, the mentioned fixes are all separated by different commits.
If you find some time you could have a look at the changes.
=> [Search Map] Some fixes after tech update

gc_little_helper_II.user.js
Added support for the #GCType# placeholder in log and message templates. Only for the new logging experience (I believe the old logging page is not accessible any more).
Identifies cache type from the cache type icon using whatever selector is available for the page it is on.
=> [Log Form] Added placeholder cache type to signature and log templates

data/config_standard.txt, gc_little_helper_II.user.js
close #2419
- Beispiele: GC8NA1H, GCA4YT5, GC4T7NH, GC7YRJN, GC9C0TF, GC1RZ81, GCAJHWN (Unschön: Stadtgebiet Bremen)
- Das Problem mit "Stadtgebiet ..." scheint es nur in Bremen zu geben und es ist nur eingeschränkt vorhanden. Auch ansonsten habe ich keine Probleme mehr gefunden bzw. konnte sie ausbügeln.
- Geeignete Länder: de, at. Darauf ist die Erweiterung auch beschränkt.
- Nicht geeignete Länder weil Daten fehlen oder die Felder und teils auch die Namen selbst ganz anders sind: ch, cz, fr, li. Ich habe es bei meinen Tests dabei belassen.
- Sprachen: Country in Englisch so wie im Cache Listing, Bundesland und Landkreis ... in Deutsch.
---
https://www.geocaching.com/my/#GClhShowConfig#a#settings_maps_add_county_to_place
With this option, the county is added to the location of the cache …
=> [Cache Listing, Maps] Add county (Landkreis) to cache location

gc_little_helper_II.user.js
If you select and save the config on public profile, the url after the refresh is no longer `...tab=stats#profilepanel` but `...tab=stats#`.
#2700
=> [Statistic] Error in Statistics - resize find charts does not work

gc_little_helper_II.user.js
Enables #2545 after GS tech update.
=> [Search Map] Enable preserve a specified URL zoom parameter on page load

data/config_standard.txt, gc_little_helper_II.user.js
close #2716
---
Adjustments:
- Set real edit link in logs in area Latest Activity
- Copy to clipboard button for log text in Latest Activity list
- Build log texts in Markdown
- Hide TB Activity
- Show unpublished hides
- Links to GClh config, sync and changelog
- Compact layout
- Map and Search button in left sidebar
Removes:
- Show/Hide nearby events. It is now available on the standard website.
- Show cache/TB type in front of log type in Latest Activity list. It is now available in a similar form on the standard website.
=> [New Dashboard] Adjustments and removes because of the last update of the website

data/main.css, gc_little_helper_II.user.js
- Enable Linklist scrolling for long Linklists. Do not longer break the Linklist if longer than screen height.
- Enable config and sync call via F4 and F10 and do not longer call dashboard to call there config and sync. 
- Enable config and sync scrolling.
- Message about missing feature on page no longer breaks up inappropriately.
Additionally:
- Blanks at the end of a line were automatically removed.
=> [Browse Map] Enable Linklist scrolling and enable config and sync call and scrolling

gc_little_helper_II.user.js
#2708
Fix functions 'geocacheActionBar', 'addHideHeaderButton' and 'toggelHeader' after GS tech migration
=> [Search Map] Fix toggleHeader - Hide header

gc_little_helper_II.user.js
#2708
---
- Fix [Search Map] Hide header button should only be displayed when dealing with lists (Tech migration) (function geocacheActionBar function addHideHeaderButton)
---
Additional:
- Fix [Search Map] Open latest logs and personal cache note slightly late so it doesn't flutter.
- Fix [Browse Map] Open latest logs and personal cache note slightly late so it doesn't flutter.
=> [Search Map] Fix (Tech migration)

gc_little_helper_II.user.js
#2708
---
- [Search Map] Create "save as Pocket Query" button (Tech migration) (function addCreatePQButton)
---
Addition:
- Fix [Search Map] If a BML was previously active and no new search was performed afterwards, generating pocket query is not possible. 
If a BML was previously active and no new search was performed afterwards, the url parameters lat and lng are not available and generating pocket query is not possible. But there are the url parameters mlat and mlng that can be used.
=> [Search Map] Create "save as Pocket Query" button (Tech migration) (function addCreatePQButton)

gc_little_helper_II.user.js
Workaround for #2796:
Mit diesen Änderungen wird das Feature "One click ignoring" deaktiviert, damit es möglich ist, einen Cache weiterhin auf die Ignore Liste zu setzen bzw. von dort zu entfernen.
=> [Cache Listing] "One click ignoring" no longer works (workaround)

gc_little_helper_II.user.js
Selecting logs via "Order by..." doesn't work if a fixed number of logs was previously displayed, for example, via the log type icons. The exact number of logs will then continue to be displayed. It would be correct to display only the number of logs for the initial startup.
This only worked if the fixed number of logs was generated by the "Search in logs" option.
=> [Cache Listing] "Order by ..." does not work if a fixed number of logs were previously displayed.

gc_little_helper_II.user.js
closes #2796
- `__EVENTVALIDATION` and `__RequestVerificationToken` wasn't set.
- Parsing the HTML with jQuery make the reading of the values more robust
=> fix(Cache Listing): One Click ignore

.vscode/settings.json, gc_little_helper_II.user.js
#2507
By scrolling to the issue list, I had an idea to solve this. It's not an intuitive solution, but a solution used by many other programs, where ctrl+enter has another meaning than just pressing enter.
With the approach the behavior of the navi search stays the same, but if you use ctrl+enter, you can force, searching a tracking code.
If the code is not 6 digits, it falls to the default behavior and looks for GC, TB, etc codes.
=> feat(Navi Search): force searching for tracking code

gc_little_helper_II.user.js
This PR is a major improvement for displaying geocaches at corrected coordinates:
1.  no calls to searchThisArea necessary anymore (i.e. server load is reduced)
-  on initial page load
- when switching between corrected and original coordinates
2. enabling/disabling of corrected coordinates button now works more reliable (there were some corner cases)
Additionally, retrieving a handle to the Leaflet map is now less complex and requires fewer resources.
These changes were only possible due to #2822 and therefore are based upon that PR. 
All has been tested in Chrome, FF and Linux.
When reviewing #2822, it's maybe best to review directly this PR, since all changes and enhancements are combined.
All in all, these changes make the code less complex, more robust, easier to maintain, require …
=> [Search Map] Fix issues from tech migration

data/config_standard.txt, gc_little_helper_II.user.js
This PR adds an option to hide DNF icons and also provides the more general possibility to collect multiple cache display options in one single option button.
In detail:
- Option to hide DNF icons (also by default)
- Replace corrected coords button by a more general display options button
- add show found caches at corrected coords option
- add hide DNF icons option
Closes #2276.
Once this is merged, more display options like hide past events, hide found and owned caches, hide all cache types, ... could be added easily.
=> [Search Map] Hide DNF smileys (by default)  / Show Cache Type instead of DNF smiley

gc_little_helper_II.user.js
When running GCTour printview from a cache listing, two gclh errors occur:
1. `Copy to clipboard: Cannot read properties of undefined (reading 'parentNode')`
2. `Cannot read properties of null (reading 'top') at gclh_dynamic_load (`
This MR fixes both errors.
=> [Cache Listing] Improved interaction with other user script
