- gc_little_helper_II.user.js
- Another bug fix for the colorpicker
> Chrome Tampermonkey bug fix

- gc_little_helper_II.user.js
Die Änderung sollte machen, was in Issue 23 gewünscht ist. Hab mal ein neues Setting am "Ende" der Config-Liste eingetragen. Getestet hab ich es unter Chrome, sollte aber auch auf anderen aktuellen Browsern laufen.
> fix for https://github.com/2Abendsegler/GClh/issues/23

- gc_little_helper_II.user.js
move static configuration data into function constInit and write it much compacter
no new layers was added ore removed
no feature change
> Refactoring map layers configuration

- gc_little_helper_II.user.js
- add additional check for date/time of last Check (now "reset") if _auto reset_ for counter ist set 
- change "Last check was ..." to "Last reset was..."
> Fixed Issue #238: Friends page: "Last check" stuck

- gc_little_helper_II.user.js
> Revert "Implementation Dropbox API v2"

- gc_little_helper_II.user.js
> Revert "Teste mal ob das angerechnet wird"

- gc_little_helper_II.user.js
> Revert "Revert "Implementation Dropbox API v2""

- gc_little_helper_II.user.js
Ich habe mich mal hingesetzt und die FloppsMap-Funktionen so umgebaut, dass ich damit Links zu BRouter bekomme, die dann automatisch ein Routing über die mitgelieferten Wegpunkte erzeugen. Das spart mir bei langen Multis wie z.B. Donauradlerin https://coord.info/GC6TH34 das manuelle Hinzufügen aller Wegpunkte in die BRouter-Karte, wenn ich mir die Tour noch etwas anpassen und dabei die originalen Wegpunkte berücksichtigen will. Funktioniert bei Listings gut, in denen ausschließlich nur die Stationen drin sind. Sind am Ende der Wegpunktliste noch Wegpunkte drin, die am Anfang oder zwischendurch in der Strecke liegen, wird natürlich "zurück geroutet" wie man bei https://coord.info/GC3JH5D oder https://coord.info/GC53HQM sehen kann. Aber wer sich mit Brouter auskennt, wird wissen, wie er den …
> BRouter-Link

- gc_little_helper_II.user.js
- make map only dragable in south-direction
- added south handle to indicate map is dragable
> changes to TB-Map

- gc_little_helper_II.user.js
> Revert "Trackable Map: Changed Marker Styling"

- gc_little_helper_II.user.js
> Revert " Bugfix: Edit und Image Link bei eigenen Caches gehen nun wieder"

- gc_little_helper_II.user.js
Button for quick acces to map and search page
> Add MAP and Search button to left menu

- gc_little_helper_II.user.js
better working with images in background... small improovment :)
> change size background image in bio

- gc_little_helper_II.user.js
EDGE return "undefined"
FireFox return empty string
> Correction for EDGE - problem with "window.name"

- gc_little_helper_II.user.js
> #594 If user not logged in and visiting a cache page directly, he has no chance to sign in

- gc_little_helper_II.user.js
Issue #601und wieder geöffnetes Issue #594.
> On Friend League page social sharing Twitter do not hide due to changes made by GS

- gc_little_helper_II.user.js
> On new dashboard search button is moved due to changes made by GS

- gc_little_helper_II.user.js
> Draft count is also displayed at project GC button

- gc_little_helper_II.user.js
```
-            html += "&nbsp;&nbsp;&nbsp;" + "First service: <select class='gclh_form' id='settings_secondary_elevation_service' >";
+            html += "&nbsp;&nbsp;&nbsp;" + "First service: <select class='gclh_form' id='settings_primary_elevation_service' >";
```
> Save in Config does not work.

- gc_little_helper_II.user.js
Außerdem hab ich noch titles für die Favoritenprozente, Premium Only Icon und Anzahl Trackables auf dem MapEnhanced Popup hinterlegt, ausgelöst dadurch dass womöglich nicht jeder das Premium Only Icon kennt.
> v0.9.6 go live

- docu/changelog.md
- gc_little_helper_II.user.js
https://github.com/2Abendsegler/GClh/issues/662#issuecomment-389917634
> Search field color #662

- docu/changelog.md
- gc_little_helper_II.user.js
https://github.com/2Abendsegler/GClh/issues/674#issuecomment-390394055
> Search map buttons

- gc_little_helper_II.user.js
> #672: implement number of souvenirs

- gc_little_helper_II.user.js
This fix the bug #746, element and id has changed by GS
> #746 fix detection of Personal Cache Note

- gc_little_helper_II.user.js
> No favorites in percent in map on additional popup #766

- gc_little_helper_II.user.js
- implement an alert for gclh_error. 
- feature is optional
- create a new section at settings dialog: Development
- feature is inactive by default
> Alert if gclh_error is called (#752)

- gc_little_helper_II.user.js
> Feature added

- data/config_standard.txt
- gc_little_helper_II.user.js
> Auto open TB List on Logpage

- gc_little_helper_II.user.js
bugfix - use unsafeWindow.mapLatLng structure to get cache type and coordinates
> Merge #787: Small Map in Cache Listing shows Error

- gc_little_helper_II.user.js
Der Doppelpunkt wird mittlerweile zentral gesetzt. Ich dachte das ist mal ne richtige stupid Arbeit, die ich heute Abend gerade noch hinbekomme. :)
> Only delete double colon in error message.

- gc_little_helper_II.user.js
Getestet unter FF auf der Karte und auf der Search Seite.
> Unification of the line spacing and font size of "Add to list" popup #905

- gc_little_helper_II.user.js
> New install counter #909

- gc_little_helper_II.user.js
> Process icon "Copy GC Code to clipboard" also on additional Popup in maps #911

- gc_little_helper_II.user.js
Getestet für Inline Log und PMO Inline Log. 
Ein Log hab ich aber nicht gebucht. Kannst du das bitte noch machen.
> Log inline and PMO log inline on Listing not work #888

- gc_little_helper_II.user.js
Länge der Kartenbezeichnung begrenzt.
> Small map #865

- gc_little_helper_II.user.js
> "Mark Caches with Corrected Coordinates" doesn't work on foreign bookmark lists. #928

- gc_little_helper_II.user.js
> #941 Error on friends page in section Pending Friend Requests.

- gc_little_helper_II.user.js
Upload js.
Die Änderung zieht nur fürs TB Listings. Cache Listing und andere Listing müssen nicht getestet werden.
@Ruko2010 
Kannst du bitte noch für Chrome testen.
> #943 Error on Emtpy Trackable Pages

- gc_little_helper_II.user.js
> #939 Destroyed style of icons on search page for manage filter sets.

- docu/changelog.md
> Prepare go live v0.9.16

- gc_little_helper_II.user.js
Changelog, Screens und Startkonfiguration sind im PR Prepare ...
> Show log counter when opening cache listing. #954

- gc_little_helper_II.user.js
Getestet unter Win 8.1 mit FF und Chrome.
> Hide sidebar on map doesn't work with open in new tab. #967

- gc_little_helper_II.user.js
Es wird mal wieder mehr als geändert ausgewiesen als tatsächlich geändert wurde. 
GM_xmlhttpRequest wurde lediglich in eine function gepackt und context darin wurde um additionalListingIndex erweitert.
> #976 geonames elevation

- gc_little_helper_II.user.js
@2Abendsegler do you have a look at it?
> #975 Display difficulty/terrain in bookmark lists

- gc_little_helper_II.user.js
Close button now goes back to config.
Außerdem habe ich noch zwei Zeilen Beschreibung hinzugefügt wie die Liste zu pflegen ist.
> Note of thanks #1004

- data/config_standard.txt
- gc_little_helper_II.user.js
Erweiterung Changelog, siehe Issue #1009.
> Show log totals symbols #1009

- gc_little_helper_II.user.js
Foreign bookmarklist
https://www.geocaching.com/bookmarks/view.aspx?guid=ea3e6b54-19e3-4186-b6a4-dd0e27de2cfe
> Missing button create pocket query on foreign bookmarklists. #1012

- data/config_standard.txt
- gc_little_helper_II.user.js
> Build back old designed page list of bookmark lists. Rename link list of bookmark lists to new designed page. #1015

- gc_little_helper_II.user.js
> Remove all functions for logtable, if there is none (unpublished caches)

- gc_little_helper_II.user.js
Bezeichnung des Buttons dynamisch setzen. "Show compact logs" und "Hide compact logs". 
(Wollte nur etwas spielen.) 😊
> Button for hiding lot of stuff in the logs #1045

- gc_little_helper_II.user.js
Außerdem Config Kleinigkeiten: 
- Feld Home coords verlängern.
- Homezone Feld Home coords verlängern.
- Layers in map: Breite der Felder vergrößern.
- Openrouteservice Medium Feld verkürzen.
> No coloring of TB listing. #1074

- data/config_standard.txt
- gc_little_helper_II.user.js
Umsetzung der Issues 
[1095](https://github.com/2Abendsegler/GClh/issues/1095)
[1096](https://github.com/2Abendsegler/GClh/issues/1096)
> Add data 2 clip

- gc_little_helper_II.user.js
- searchmap link in Linklist.
- Berichtigung </select> ohne folgendes br.
- Etwas Doku
> Kleinigkeiten

- gc_little_helper_II.user.js
> Improve GC Search to Geo tours

- gc_little_helper_II.user.js
Reverts 2Abendsegler/GClh#1134
> Revert "The add to list loading and success message in cache listing are displaced. #1133"

- gc_little_helper_II.user.js
Hide hints in cache listing behind a link with show/hide do not decrypt.
Improve print page cache listing with hide disclaimer, decrypt hints, show other coord formats and hide side rights does not run.
> Cache Listing with many errors. #1153

- gc_little_helper_II.user.js
> Improve character counter on the new Logging Page and show length of hint, geocachename and placed by on the hide/edit page.

- gc_little_helper_II.user.js
> All routing services in cache listing do not work proper because of GSs GDPR changes. #1181

- gc_little_helper_II.user.js
> Error on new Lists page. #1227

- gc_little_helper_II.user.js
Die Funktion wurde mehrfach aufgerufen. Jetzt sollte es funktionieren.
> Show hint automatically

- gc_little_helper_II.user.js
- Link zu laden der Statusmeldung
- Caches mit fadeIn/fadeOut ein- bzw ausblenden und border hinzugefügt, damit sich die Box besser ins Dashboard einpasst.
- Config Parameternamen an restliches Config angepasst.
> Unpublished hides were shown in recently viewed list after an update from GS

- gc_little_helper_II.user.js
@Ruko2010 
Kannst du dir das bitte ansehen? Können wir das so machen?
> Edge no longer works with gclh

- gc_little_helper_II.user.js
#1253 
@Ruko2010 
Kannst du kurz drüberschauen, ob das so ok ist?
> Show own specified entry in menu of copy data to clipboard

- gc_little_helper_II.user.js
fix #1273 
- Show number of words behind the loglength.
- Rename limitLogText() to limitedField()
> Show number of words behind the loglength.

- gc_little_helper_II.user.js
> Refactor helper functions #772

- gc_little_helper_II.user.js
> Set link to owner

- gc_little_helper_II.user.js
> Show weekday for community celebration events.

- gc_little_helper_II.user.js
Apply map config settings on new search map (set filter on map load)
> Map config settings on new search map (set filter on map load)

- gc_little_helper_II.user.js
Only one new line:
`8506  if (document.location.href.match(/\.com\/play\/map(\/BM|\?bm=)/)) return;`
Other changed lines are "tab in space" changes.
> Don't set filter on new map load of BML

- gc_little_helper_II.user.js
> Hide and show Community Celebration Events together with normal Events

- gc_little_helper_II.user.js
@capoaira:
Kannst du bitte die Änderungen testen, so weit das möglich ist? 
Im Config sieht das teilweise nicht ganz so schön aus wegen der langen Namen der Links. Aber da müssen wir durch. 😁
Ich habe auf Win10 die Browser FF, Chrome und Edge getestet.
Hast du auch einen Mac? Ansonsten muss Ruko2010 ran. 😁
> Build up new links in linklist - Upload js

- gc_little_helper_II.user.js
> Owner dashboard] build up the new links in linklist

- gc_little_helper_II.user.js
> Correct position - upload js

- gc_little_helper_II.user.js
> Get favorite score and own favorite point in cache listing - upload js

- gc_little_helper_II.user.js
> Description of the inline logs supplemented by the uBlock add on - upload js

- gc_little_helper_II.user.js
> Build links to the log section, at the top log totals - upload js

- gc_little_helper_II.user.js
> Change link from coords.info to coord.info - upload js

- gc_little_helper_II.user.js
Reverts: 2Abendsegler/GClh#1419
> Revert: "Erweiterung zu "copy data to clipboard" #1365"

- gc_little_helper_II.user.js
#1287
Resize funktioniert wieder und das auch ohne graue Balken.
Maus Wheel Zoom geht auch.
> Build resize tb-map - upload js

- gc_little_helper_II.user.js
> Addition of data to clipboard #1365

- gc_little_helper_II.user.js
This Branch is based on #1403. Please Merge that PR first
> [Owner Dashboard] Add link to own Profil

- gc_little_helper_II.user.js
Anpassung datumsabhängige Feldnamen
#1353
> Create direct "Edit log"-links

- gc_little_helper_II.user.js
Prüfung auf Anzeige der TotalLogs oben verbessert
> GClh hides Logs #1429

- gc_little_helper_II.user.js
Dropdown menu alignment corrected - Upload js
#1435
> For basic member the dropdown menu in premium cache listings are not aligned properly

- gc_little_helper_II.user.js
> Additional link for logging premium caches for non-premium cachers

- gc_little_helper_II.user.js
Reverts 2Abendsegler/GClh#1442
> Revert "View who favorited the cache in the logs of cache listing"

- gc_little_helper_II.user.js
> View who favorited new

- gc_little_helper_II.user.js
- Aktualisieren beim runterscrollen in den Logs.
- Verzögerung des Klicks auf next um 1 Sekunde zum Testen.
> View who favorited the cache in the logs of cache listing. #1054

- gc_little_helper_II.user.js
> Highlight found places from cache listing "Search in logtext" in the logs - Upload js

- gc_little_helper_II.user.js
#1371 
So viel macht es nicht aus, aber so wird nur soviel geladen, wie geladen werden muss.
> load unpublished caches faster

- gc_little_helper_II.user.js
> Show behind the "Add to list" button if cache is available in own bookmarklists

- gc_little_helper_II.user.js
#1372
Message icons konnte ich nicht bilden, da ich nicht an die guid gekommen bin.
> [Owner Dashboard] Build VIP, VUP, Mail icons

- gc_little_helper_II.user.js
> #1490 Adjust smileys on new log form

- gc_little_helper_II.user.js
> Adjust alignment and height of the "log templates" field

- gc_little_helper_II.user.js
#1493 
- Button to other map services
- Relocate button to browsemap
> fix buttons on the right are missing

- gc_little_helper_II.user.js
> signature is not insert into new logform

- gc_little_helper_II.user.js
#1485 
Bitte einmal drüber gucken, falls ich eine Funktion übersehen habe.
> Not all GClh features run if log form is called from dashboard

- gc_little_helper_II.user.js
> After change of bookmark go to bookmark list automatically - upload js

- gc_little_helper_II.user.js
[New Dashboard] Simplification edit button on dashboard. #1465
> Simplification edit button on dashboard.

- gc_little_helper_II.user.js
> Show behind the "Add to list" button if cache is available in own bookmarklists does not work

- gc_little_helper_II.user.js
> fix Hide found/own caches, cache types

- gc_little_helper_II.user.js
> [New Map] Remove code for "Align logs again correctly in the detail screen" because GS has fixed it.

- gc_little_helper_II.user.js
> Change of the language does not affect the header of the new map

- gc_little_helper_II.user.js
> [New Map] Show hint automatically does not work always / Refactor show hint automatically

- gc_little_helper_II.user.js
> [New Map] Loading Spinner is visible if "Automatic search for new caches after dragging" is off

- gc_little_helper_II.user.js
> Automatic search after zooming

- gc_little_helper_II.user.js
> [Public profile] Both trackables lists are not displayed side by side.

- gc_little_helper_II.user.js
> fix Automatic search of new caches is available also for bookmarklists maps

- gc_little_helper_II.user.js
> [Hide cache] Build header with navigation menu and linklist.

- gc_little_helper_II.user.js
> Popups with corrected coordinates

- gc_little_helper_II.user.js
> Migrate elevation parameters first service to 'GeoNames' and second service to 'Open-Elevation'.

- data/config_standard.txt
- gc_little_helper_II.user.js
> Add feature to show/hide the cache description in bookmark lists and ignore list.

- gc_little_helper_II.user.js
> [Find player] Link "Find Player" from Linklist doesn't work.

- data/config_standard.txt
- gc_little_helper_II.user.js
> [Lists] Upload caches to a bookmark list from .gpx or .loc file, or from file with seprarators.

- gc_little_helper_II.user.js
set the URL to the service to the old version, which is still
available. This should considered being an intemediate solution as I
didn't find an statement saying how long this link will be available.
> Openroutemaps has been changed and the links does no longer work.

- gc_little_helper_II.user.js
> Build VIP, VUP, Mail icons does not work correct on COD

- gc_little_helper_II.user.js
> gallery link does not work on gclh area

- gc_little_helper_II.user.js
GClh Search can now search for Bookmarklists, Profiles and Logs by code (BMXXXXX, PRXXXXX, GLXXXXXXX)
#1586
> Improve GClh Search to Bookmarklist, Profile and Logs

- gc_little_helper_II.user.js
> Oneclick watching does not work

- gc_little_helper_II.user.js
> Bug without PQs

- gc_little_helper_II.user.js
> fix number was not shown on one click watching

- gc_little_helper_II.user.js
> [New Map] Integrate new BML feature in compact layout feature

- gc_little_helper_II.user.js
> Classify souvenirs by country, state and other.

- gc_little_helper_II.user.js
Reverts 2Abendsegler/GClh#1604
> Revert "Classify souvenirs by country, state and other."

- gc_little_helper_II.user.js
Reverts 2Abendsegler/GClh#1600
> Revert "[New Map] Integrate new BML feature in compact layout feature"

- gc_little_helper_II.user.js
> Vip Vup Mail

- gc_little_helper_II.user.js
> [New Map] Integrate new BML feature in compact layout feature 2

- gc_little_helper_II.user.js
> [Souvenirs] Classify souvenirs by country, state and other.

- gc_little_helper_II.user.js
#1612
- [Cache listing] One click ignoring corrected.
- [Cache listing, New log form, Old log form, Friends, TB listing, Mail, TB log form, TB inventury] VIP, VUP, mail, message corrected.
- [TB listing] VIP, VUP, own, owner, reviewer coloring in TB listing corrected.
- [Cache listing] Counter of "Add to List" corrected.
> User related features don't work correct on several pages.

- docu/changelog.md
- gc_little_helper_II.user.js
> GoLive v0.10.14

- gc_little_helper_II.user.js
> Change links to found/hide caches to the old link

- gc_little_helper_II.user.js
> fix hide sidebar by default on list view

- gc_little_helper_II.user.js
> Save as PQ button on search map

- gc_little_helper_II.user.js
> GS menue do not work with no "change header layout" and no "Linklist on top". 

- gc_little_helper_II.user.js
#1661 
Details siehe [hier](https://github.com/2Abendsegler/GClh/issues/1661#issuecomment-827398263).
> [Souvenirs] GS has now an own souvenirs sort feature. Display group of souvenirs do not work.

- gc_little_helper_II.user.js
> fix save as pq was visible on list view

- gc_little_helper_II.user.js
> Print page cache listing has coords format error

- gc_little_helper_II.user.js
> "Found" placeholders do not work.

- gc_little_helper_II.user.js
remove whitespace from both ends of the navi_search value
> remove whitespace from navi_search

- gc_little_helper_II.user.js
> GClh does not always run if finds are null

- gc_little_helper_II.user.js
[New Map] Shows white screen. #1595
> [New Map] Shows white screen.

- data/gclh_defi.js
- gc_little_helper_II.user.js
> [Old Map] Install layer ÖPNVMap.

- gc_little_helper_II.user.js
> Change links to hide caches to the old link do not work for basic members.

- gc_little_helper_II.user.js
> Break of the Linklist in the header with horizontal menu.

- gc_little_helper_II.user.js
[Listing] Show icons to new and old map in overview map. #1692
Upload js
> Show icons in overview map

- gc_little_helper_II.user.js
> Open Personal Cache Note in minimum size

- gc_little_helper_II.user.js
> [Config] New structuring of the topics "Global" and "Listing" in config.

- gc_little_helper_II.user.js
> Make internal Linklist calls available on all possible pages.

- gc_little_helper_II.user.js
> Hide upvote feature

- gc_little_helper_II.user.js
[Cache listing] "Great story" and "Helpful" Button does not work. #1622
[Cache listing] Hide upvote feature with logs sort and "Great story", "Helpful" buttons. #1623
[Cache listing] Make upvotes icons for "Great story" and "Helpful" smaller. #1702
[Cache listing] No wiggle on click to upvotes buttons "Great story" and "Helpful". #1703
> Upvotes feature - Upload js

- gc_little_helper_II.user.js
> Improve alignment of icons.

- gc_little_helper_II.user.js
Upload js
[Souvenirs] Show more than four souvenirs in a row again. #1712
(Also: Change cursor from not allowed to default on new page.)
> Show more than four souvenirs in a row again

- gc_little_helper_II.user.js
> Activate compact layout on pocket queries again.

- gc_little_helper_II.user.js
> VIP, VUP and Mail for owner in new map.

- gc_little_helper_II.user.js
Auch ohne Compact Layout
#1593
> VIP, VUP and Mail for owner in new map

- gc_little_helper_II.user.js
> [Public Profile / Souvenirs] Standard sort changed to newest first as it is done on the souvenirs page.

- gc_little_helper_II.user.js
> Correct links in Linklist

- gc_little_helper_II.user.js
> Do not break the column "View log" in my Geocaching Logs and my Trackable Logs

- gc_little_helper_II.user.js
> Build back coding of the old profile page.

- gc_little_helper_II.user.js
> Prepare go live v0.11.1 - Upload js

- data/config_standard.txt
- gc_little_helper_II.user.js
> GoLive v0.11.1

- docu/changelog.md
- gc_little_helper_II.user.js
[Global / Chrome] "switch" handling in Chrome inconsistent (Chrome bug).
#1743
Upload js
> GoLive v0.11.2

- docu/changelog.md
- gc_little_helper_II.user.js
Script does not work because of missing user data due to changes made by GS.
Last affected pages:
- New Log Form
- [Search](https://www.geocaching.com/play/search) 
- [Leaderboard](https://www.geocaching.com/play/leaderboard) 
- [Geotours](https://www.geocaching.com/play/geotours) 
- [Guidlines](https://www.geocaching.com/play/guidelines) 
#1755, #1757
> GoLive v0.11.3

- gc_little_helper_II.user.js
Hallo Frank,
habe mir den guthub client installiert und mich etwas damit versucht.
Hoffe, ich habe das richtig gemacht.
VG
Patrick
> [map overview] open map in new tab

- gc_little_helper_II.user.js
> cod fix set link to profile

- README.md
- data/config_standard.txt
- docu/faq.md
- gc_little_helper_II.user.js
> Some little things

- gc_little_helper_II.user.js
> Hide Header on Search Map

- gc_little_helper_II.user.js
[Search Map] Space around the header without "Change header layout". #1762
[Owner Dashboard] Set Link to Profile does not work #1765
> Spave header and Owner Dashboard profile link

- gc_little_helper_II.user.js
> Correct the order when opening selected caches in new browser tabs for Chrome.

- gc_little_helper_II.user.js
> No dropdown with map selection for map services under waypoint table

- gc_little_helper_II.user.js
[Global] Handle the key combination ctrl + s like the key F2.
[Global] Disable user profile menu by clicking anywhere else.
> revision config

- gc_little_helper_II.user.js
> [Owner Dashboard] GClh does not work after changing view

- data/gclh_defi.js
- gc_little_helper_II.user.js
[Search Map / Browse Map / Pocket Query] Before saving as PQ from map, determine whether the GClh default settings for new PQs should be set or not.
#1574
> Pq set defaults

- gc_little_helper_II.user.js
https://github.com/magma1447/greasemonkey-geocaching-projectgc/pull/99
#1783
Only merge if https://github.com/magma1447/greasemonkey-geocaching-projectgc/pull/99 is merged
> account setting menu also open pgc menu

- gc_little_helper_II.user.js
> Upvote buttons and log edit button are not displayed for basic members.

- gc_little_helper_II.user.js
#1786
@Ruko2010 könntest du hier kurz drüber schauen? Bei @2Abendsegler sind noch nicht genug Logs vorhanden.
> [Owner Dashboard] No VIP, VUP, Mail icons if "Load More" button below the logs is clicked

- data/gclh_defi.js
- gc_little_helper_II.user.js
[Config] Rebuild config and config color schemes.
> Collection of changes

- gc_little_helper_II.user.js
- Neue show/hide Icons.
- Bezeichnungen und Hilfstexte überarbeitet im Hinblick auf eine Übersetzung. 
- Altes Coding ohne checkboxy umgebaut.
- Neues Feature Farbschemas fertiggestellt.
> Überarbeitung Config abgeschlossen

- gc_little_helper_II.user.js
#1370
Ich habe vorallem in der sidebar die Abstände verringert. Bei den Logs wird mir vieles zu unübersichtich, wenn dort mehr zusammenfassen würde.
> [Owner Dashboard] Compact Layout

- gc_little_helper_II.user.js
Handle both modi .mobile-log-item-wrapper and .log-item in compact layout, with vip, vup, mail icons.
#1370
> Owner dashboard compact layout

- gc_little_helper_II.user.js
> [Owner Dashboard] Add the favorite percentage in the cache list

- gc_little_helper_II.user.js
[Search Map] Error message "Sorry, we couldn't find what you're looking for". #1785
> collection-of-changes

- gc_little_helper_II.user.js
> [Public Profile] GS's souvenir sorting is now also available in the public profile. Our sorting and hiding functions need to be changed.

- gc_little_helper_II.user.js
Mein Fehler. Ist wohl schon ne ganze Weile so, seit der Umstellung der Suche von Profile Links von ...`profile`... auf ...`(profile|p)`... . Ich habe geprüft ob mir noch einer durch die Lappen gegangen ist, war aber nicht so.
@capoaira 
Kann du bitte noch mal drüber schauen. Und dann ab in den collector.
> [Leaderboard] VipVupMail does not work

- gc_little_helper_II.user.js
Upload js
Die Amis spinnen. 😬 Jetzt haben die die User Daten in mehrere Bereiche aufgeteilt. Ich frage jetzt alle Felder einzeln ab. Vielleicht passt das jetzt etwas länger.
Ich habe alle Links aus der Linklist durchgetestet für ein Basis Member mit 0 Finds, für ein Basis Member mit > 0 Finds und für ein Premium Member mit > 0 Finds. Passt alles.
Bitte nur noch mal kurz für die neue Karte bei Dir testen, nicht dass ich wieder irgendwo 2Abendsegler stehen habe. 😂  
Kannst dann auch mergen, wenns passt und wenn du möchtest.
> [New Map] Undefined Finds

- gc_little_helper_II.user.js
> Button for [Owner Dashboard] Add the favorite percentage in the cache list

- gc_little_helper_II.user.js
#1822 
- using new url for ajax call
- rename `nr` to `watchNr`
> fix one-click watching / add one-click unwatching

- gc_little_helper_II.user.js
#1822
Möglichkeit zum Mehrfachklicken abgestellt.
> [Cache Listing] One-click watching does not work / One-click unwatch possible

- docu/tips_installation.md
> Tampermonkey link for safari does not work

- gc_little_helper_II.user.js
#1843 
- fix #GCNote# on copydata for own stuff
- remove double #GCLink# on Possible placeholders
> fix #GCNote# on copydata for own stuff

- gc_little_helper_II.user.js
> fix display personal cache note on map

- gc_little_helper_II.user.js
Reverts 2Abendsegler/GClh#1846
> Revert "fix display personal cache note on map"

- gc_little_helper_II.user.js
#1863
- Text Fehlermeldung angepasst.
- Position der Versorgung der speziellen Linklist Links verschoben, so dass sichergestellt ist, dass die Linklist aufgebaut ist bevor sie geändert wird.
> Nearest links and own trackable link from Linklist don't work.

- gc_little_helper_II.user.js
#1867
- Und Meldungen möglichst nicht mehr selbst umbrechen.
> Errormessage after press button "Save & Upload" has wrong text if there is no authentication.

- gc_little_helper_II.user.js
#1856 
Den Fehler habe ich durch den letzten Fix #1837 verursacht.
> Watch Button on unpublished cache.

- gc_little_helper_II.user.js
> Map layer replacement Violentmonkey

- gc_little_helper_II.user.js
Beachten < und > in Username
#1861
> [Public Profile] Links "show hides" and "show finds" don't work for user ">Doppelherz<".

- gc_little_helper_II.user.js
> Log in button missing

- docu/changelog.md
- gc_little_helper_II.user.js
- Config Thanks Seite: Spalte Development für Lead ergänzt.
- Cache Listing: Icons auf Overview Map besser ausrichten wenn nur ein Icon angezeigt wird.
- Cache Listing: Alignment and look of personal cache note.
- Search Map: Alignment of sidebar header.
> Prepare go live v0.11.5.2

- gc_little_helper_II.user.js
> fix d/t rating on save as pq

- gc_little_helper_II.user.js
> Templates and Smilies missing, Placeholders and Signature does not work

- gc_little_helper_II.user.js
#1887 
Ich habe anders als im Issue beschrieben keinen großen Umbau des Features gemacht, sondern nur den Bug gefixed. 
Die Filter Sets in das Popup zu integrieren wäre eine größere Arbeit, die ich mit #1504 umsetzen würde.
> Button to GClh-Filtersets not visible

- gc_little_helper_II.user.js
> Remove One-Click Watching

- gc_little_helper_II.user.js
> [Browse Map] Enable non GClh layers like GME or GC.

- gc_little_helper_II.user.js
> Check if the old GC little helper is running

- gc_little_helper_II.user.js
#1911
So, jetzt nochmal ohne das Wirrwarr aus dem anderen PR
> fix signature on drafts

- gc_little_helper_II.user.js
> Automatic opt out to the old log form with a draft run into error on old log form  and add a try, catch statement

- gc_little_helper_II.user.js
> Prevent popup when clicking on "Watch" or "Stop Watching"

- gc_little_helper_II.user.js
> [Search Map] After clicking the back button in the cache detail screen, the positioning in the list of caches doesn't work.

- gc_little_helper_II.user.js
> [Search Map] Button "Browse geocaches" remains, even if it is relocated to the other buttons.

- gc_little_helper_II.user.js
Fix [Search Map] The GClh default filters setting change map zoom.
New [Search Map] Don't display the filters screen during the GClh default filters setting are running.
Upload js
#1921
> Revision GClh default filters setting

- gc_little_helper_II.user.js
> [Search Map / Search] Implement F2 key functionality on "Apply" button of the filters screen.

- data/main.css
> [Search Map] Header has white space border if "Change header layout" is disabled.

- gc_little_helper_II.user.js
> [Cache Listing] Limit the number of logs to be displayed when opening the Listing.

- gc_little_helper_II.user.js
> [Cache Listing] Integrate the new styled upvotes element "Order by" in the available settings.

- data/config_standard.txt
- data/header.html
- gc_little_helper_II.user.js
Upload js
Upload header.html with upgrade button
Update config_standard.txt with new parameter
#1835
> [Global] Hide upgrade button in header with new parameter (basic member).

- data/main.css
Reverts 2Abendsegler/GClh#1944
> Revert "[Search Map] Header has white space border if "Change header layout" is disabled."

- data/main.css
#1936
Änderung der main.css
So, eigentlich hat der Header grüne Hintergrundfarbe. Warum die nicht angezeigt wird, ist mir auch immer noch ein Rätsel.
Ich habe aber eine andere Lösung gefunden.
> Handle wide screens on search map

- gc_little_helper_II.user.js
> [Cache Listing] "Go to Logs" doesn't work.

- gc_little_helper_II.user.js
> Cache listing ugly display in add to list popup

- gc_little_helper_II.user.js
> [Browse Map] No "Hide/Show all Cachetypes" buttons if we comes from pocket query.

- gc_little_helper_II.user.js
> [Cache Listing] Display "Image not available" is wrong.

- gc_little_helper_II.user.js
> [Global] Check if the old GC little helper is running.

- gc_little_helper_II.user.js
> [Pocket Query] Some default values are not set if the PQ is created from map. Keep "Set default" parameter in mind.

- gc_little_helper_II.user.js
> [Search Map] Sometimes there is a line break between the cache type icon and the cache name in the cache details screen.

- gc_little_helper_II.user.js
> [My Lists] Compact layout doesn't always work.

- gc_little_helper_II.user.js
> [Log forms] Prevents a message from being displayed if the log is not saved.

- gc_little_helper_II.user.js
> [Browse Map] Optionally an alphabetical sorting of the layers in the selection display on the map.

- gc_little_helper_II.user.js
> [Statistik Matrix] Possible D/T combinations no longer works.

- gc_little_helper_II.user.js
> [Cache Listing] Revision of "Search in logs".

- gc_little_helper_II.user.js
> [Cache Listing] Improve screen "Enter solved coordinates".

- gc_little_helper_II.user.js
> [Cache Listing] Activate little Christmas hats in latest logs.

- gc_little_helper_II.user.js
> [Cache Listing] Let icons on overview map gray separately when hovering.

- gc_little_helper_II.user.js
> [Log forms] Double signature in both log forms when coming from the drafts.

- gc_little_helper_II.user.js
> [Config] Handle the key combination ctrl + s like the key F2 to save config.

- gc_little_helper_II.user.js
Place the cursor directly in the input field.
Enable the search to be started by pressing the Enter key.
#1996
> [Trackable search] Simplify trackable search.

- gc_little_helper_II.user.js
> [Log forms] Show number and percentage of favorites and number of watcher.

- gc_little_helper_II.user.js
> [Old Log form] Show additional cache info only in post mode.

- gc_little_helper_II.user.js
> [Search Map] Incorrect display of the search field.

- gc_little_helper_II.user.js
> [Browse Map] Special character in title of cache name in popup of additional cache data are not displayed correctly.

- gc_little_helper_II.user.js
> [Public Profile] Change links to found/hide caches to the old link no longer works

- gc_little_helper_II.user.js
> [New Log form] Improve the description of parameter "settings_show_pseudo_as_owner".

- gc_little_helper_II.user.js
> [Listing] Revise the look of the buttons above the logs.

- gc_little_helper_II.user.js
> [Pocket Query] Revise the look of the buttons.

- gc_little_helper_II.user.js
> [Cache Listing] Improve cursor when displaying or editing the personal cache note.

- data/main.css
> Submenu is displayed on wrong position on wide screens

- gc_little_helper_II.user.js
> [New Drafts] The GClh causes an error on the website

- gc_little_helper_II.user.js
> [Pocket Query] Revise the look of the buttons

- gc_little_helper_II.user.js
> Favorite percentages are displayed incorrectly

- gc_little_helper_II.user.js
> typo in settings

- gc_little_helper_II.user.js
> Pocket Query Delete Button korrigiert

- gc_little_helper_II.user.js
Umstrukturierung der Config Bereiche Pocket Query, Nearest Caches List und Recently Viewed Caches List.
#2007
> Config Umstrukturierung

- data/config_standard.txt
- gc_little_helper_II.user.js
Angefixt durch den fleißigen @capoaira habe ich ein paar Dinge zur Draft Seite entwickelt, die mich besonders nerven. 
(Entsprechende Issues habe ich noch nicht aufgemacht, werde ich nachliefern.)
Es gibt einen neuen Bereich im Config. Damit sollte sich auch erklären welche neuen Features es nun gibt. Falls nicht, werde ich nach Vorschlägen Hilfstexte einbauen.
Außerdem:
- Den alten Parameter zum Thema Draft, habe ich aus dem Config Bereich Others in den neuen Bereich Draft verschoben.
- Das Coding zur alten Draft Seite habe ich entfernt, auch den Parameter. 
- Die Config Standard Datei ist entsprechend gepflegt, auch mit den neuen Parametern.
- Im Config Bereich Listing - Overview Map habe ich eine Kleinigkeit geändert, damit dort die Zeile nicht mehr umgebrochen wird. 
- Im Config …
> Improve drafts

- gc_little_helper_II.user.js
> Open Links in a new Tab

- gc_little_helper_II.user.js
Mark current date on Finds for Each Day of the Year statistic.
> [Statistic] Mark current date on "Finds for Each Day of the Year" statistic

- data/config_standard.txt
- gc_little_helper_II.user.js
> Automatic back to Drafts

- gc_little_helper_II.user.js
Upload js
Diese Zeile war ein alter Test den ich vergessen hatte zu entfernen.
`                var fup = $(this).context.rowIndex.toString(10);`
> PQ Splitter with countries or regions with special characters

- gc_little_helper_II.user.js
Edit last log (found/dnf/will attend/ attended) from listing
> [Cache Listing] Show edit button for last log

- gc_little_helper_II.user.js
#2106
Das wäre erstmal die Funktion, wie ich sie verstanden habe, auch wenn ich nicht ganz den Sinn darin sehe, viele Templates vorzubereiten. 
Ich habe erstmal darauf verzichtet, die Funktion im Config zu erklären. Dazu ist die irgendwie zu speziell ;)
> [Log Templates] Flexible found placeholder

- gc_little_helper_II.user.js
> [Header] Horizontal Linklist with more than one line does not work

- data/main.css
- gc_little_helper_II.user.js
#2114 
Die letzte Änderung am `z-index` war #1931, das funktioniert immer noch
> color picker behind config

- gc_little_helper_II.user.js
#2089
Ich habe alles mit meinen 25 Drafts getestet. Das funktioniert. Aber mit mehr konnte ich noch nicht testen.
Ich denke wir beide sollten die Funktion testen und noch abwarten, bis einer von uns so 50-100 oder mehr zum Testen zur Verfügung hat.
> [Drafts] Statistic of cache types and log types and mark double caches

- gc_little_helper_II.user.js
Reverts 2Abendsegler/GClh#2122
Formal reasons
> Revert "[Search Map] Error message "Sorry, we couldn't find what you're looking for""

- gc_little_helper_II.user.js
This PR tries to provide a solution for #1785.
- the number of automatic searches is limited to no more than 10 per minute
- if the limit is reached, a countdown is visible and no automatic searches are performed during waiting time:
- map style changes are possible during countdown
- multiple simultaneous search map instances are taken into account
-----------------------------------
Some technical details:
1. timestamps of searches are used for the limit violation check
2. for making the timestamps persistent over multiple simultaneous search map instances, they are stored in script storage via `GM_setValue(...)`
3. countdown message simply reuses an already existing loading container
> [Search Map] Error message "Sorry, we couldn't find what you're looking for"

- gc_little_helper_II.user.js
> [Cache/TB Log] Show copy to clipboard button for Logtext and for Log ID.

- data/config_standard.txt
Update config_standard.txt
#2130
> Reset to standard configuration doesn't run.

- gc_little_helper_II.user.js
> [Browse Map] When starting with the default configuration, no map layers are displayed.

- gc_little_helper_II.user.js
> Automatic go back to Drafts after sending to log

- gc_little_helper_II.user.js
> Hide social sharing via Facebook, Twitter on souvenircampaign page.

- gc_little_helper_II.user.js
> Integration of page The Great Jerky Hunt by Jack Link's

- gc_little_helper_II.user.js
> Auto visit does not work on Events if you log from Drafts

- gc_little_helper_II.user.js
Automatic go back to Drafts after sending to log with old log form.
> [Drafts / Old log form] Automatic go back to drafts after sending to log with old log form

- gc_little_helper_II.user.js
> [Browse Map] Empty header due to a bug on the website.

- gc_little_helper_II.user.js
> [Drafts / Old log form] Bugfix - Automatic go back to drafts after sending to log with old log form

- gc_little_helper_II.user.js
Rückbau. GS hat das Problem ja mittlerweile behoben.
#2134
> [Browse Map] Empty header due to a bug on the website - Revert

- gc_little_helper_II.user.js
Upload js
#2164
@capoaira 
Kannst du dir das bitte bei Gelegenheit ansehen.
> [New Dashboard] Show cache/TB type in front of log type in Latest Activity list

- gc_little_helper_II.user.js
Add Owner Maintenance link to admin tools to right sidebar.
Certitudes Waypoint fix.
> [Cache Listing] Add for own caches the link "Owner Maintenance" to Admin Tools in the right sidebar.

- gc_little_helper_II.user.js
Fixes #2191 
Favorite score is now retrieved via web API:
`'/api/proxy/web/v1/geocache/'+gccode+'/favoritepoints/score'`
Moreover, there's now only one function for retrieval of favorite score (previously there were four):
`function getFavoriteScore(gccode, func)`
The 2nd argument is simply a function pointer that runs custom commands after the fav score arrived.
> Fix favorite score in listing, browse/search maps and old/new logging

- gc_little_helper_II.user.js
#2091 
Die letzten Zeilen (17968 ff) erweitern die Klasse `Date`. Zeile 2094 nutzt diese Funktion nun auch im Cachelisting.
Der Rest sind die eigentlichen Erweiterungen auf den beiden Karten
> Show Weekday of an Event on maps

- gc_little_helper_II.user.js
> [Browse Map] Improve clickability on list names of add to list popup.

- gc_little_helper_II.user.js
> [PQ-Splitter] "Create PQ(s)" button on Project-GC's PQ Splitter page does not work

- data/config_standard.txt
- gc_little_helper_II.user.js
Additionally: Prevent the lines in the long VIP list from breaking.
Additionally: Improvements in the css commands.
#2203
> Integrate Lackeys in VIP lists

- gc_little_helper_II.user.js
#2170 #2055
Die Änderungen sind im Coding mit `#2170 #2055` gekennzeichnet.
> Temporäre Deaktivierung des "Manage Filter Sets" Buttons bis die Funktionalität wieder hergestellt ist.

- data/config_standard.txt
- gc_little_helper_II.user.js
> Show bigger avatar image in public profile while hovering with the mouse.

- gc_little_helper_II.user.js
> GClh remove blue banner with button "Back to Drafts" after sending log related to a draft.

- gc_little_helper_II.user.js
Fixed reset button
Issue: https://github.com/2Abendsegler/GClh/issues/2205
> Friendlist fix

- gc_little_helper_II.user.js
> Download drafts

- data/config_standard.txt
- gc_little_helper_II.user.js
> Show log text in Markdown as it is in cache listing

- gc_little_helper_II.user.js
> Mark up to 10 PQs with right click.

- gc_little_helper_II.user.js
It is also possible to attach files not only images.
Solution: GCLH
Example: 
https://www.certitudes.org/certitude?wp=GC71TFG
https://www.certitudes.org/certitude?wp=GC8J1H9
> [Certitude] Error if a file is specified.

- gc_little_helper_II.user.js
upload js
#2234
@capoaira 
Kannst du bitte kurz drüber schauen.
Danke.
> Add information on how to change pop-up blocker settings on Project-GC's PQ splitter page.

- gc_little_helper_II.user.js
Some small changes to PR #2247.
> [Cache Listing] Show who gave a favorite in cache listings

- data/main.css
Change markdown-output for blockquotes
#2244
> Scripts sometimes add strange things in logs

- gc_little_helper_II.user.js
> [Cache Listing] Prevent the button line above the logs from breaking.

- data/config_standard.txt
- gc_little_helper_II.user.js
> Replace privacy text links by Icon link

- gc_little_helper_II.user.js
> [Cache Listing] Log counters are not displayed for dynamically loaded logs.

- gc_little_helper_II.user.js
> [Cache Listing] "Search in logs" is not reset when a log type selection is clicked.

- gc_little_helper_II.user.js
> [Cache Listing] Possible unneeded (and dangerous) call to append upvotes to logs

- gc_little_helper_II.user.js
> fix privacy links run into error on non-own pages

- gc_little_helper_II.user.js
#2240 
So müsste es eigentlich funktionieren. @DieBatzen könntest du nochmal testen?
> fix privacy links on emty profile

- gc_little_helper_II.user.js
This PR adds additional map layers to the Search map and closes #960.
> [Search Map] Additional map layer

- gc_little_helper_II.user.js
> Separate parameters for Browse Map and Search Map to add map layers.

- gc_little_helper_II.user.js
> Missing favorite point marker

- docu/changelog.md
- gc_little_helper_II.user.js
- Wenn settings_map_overview_build deaktiviert wird können zwei andere Parameter darunter noch angeklickt werden.
- Next check for upgrade in 8 hours.
> Prepare GoLive

- gc_little_helper_II.user.js
#2314
Punkt entfernt, damit man die Änderung auch auf dem neuen master nach Ablauf der veralteten max-age von 86400 Sekunden sehen kann.
> Test from new collector - 2

- data/config_standard.txt
- gc_little_helper_II.user.js
> [Global] Rewrite the function for remove a blue banner - activate [X] button for user interaction (2)

- gc_little_helper_II.user.js
Copy to clipboard button for log text in Latest Activity list.
> [New Dashboard] Copy to clipboard for log text in Latest Activity list.

- gc_little_helper_II.user.js
> [New Dashboard] If there are more than ten unpublished hides, the display no longer works correctly.

- data/config_standard.txt
- gc_little_helper_II.user.js
> [Event Listing] Show event time in 24 hours format.

- gc_little_helper_II.user.js
> Change possible layers for Flopp's Map pop up in listing

- docu/tips_installation.md
> Rework function keys in installation tips

- gc_little_helper_II.user.js
Beachten, dass Mail und Message deaktiviert sein könnten.
#2393
> [New Log Form] VIP, mail, message icons are not stable.

- gc_little_helper_II.user.js
> Simplification of replacement owner in log template in new log form.

- gc_little_helper_II.user.js
> [Recently Viewed Caches] Improve PQs runs into error if script send2cgeo is active.

- gc_little_helper_II.user.js
> Additional cache info favorite percentage not shown if blue banner deactivated.

- gc_little_helper_II.user.js
Log Forms show multiple cache information:
- cache type
- difficulty 
- terrain
> [Log Forms] Show further cache infos cache type, difficulty and terrain in log forms.

- gc_little_helper_II.user.js
[Cache Listing] VIP-List "Not Found" does not work on Webcam Caches bug 
#2412
> Integrate Icon 11 for webcam caches as found in VIP-Lists

- gc_little_helper_II.user.js
> Change smilies

- gc_little_helper_II.user.js
> Smilies changed

- gc_little_helper_II.user.js
> Button to copy TB Code in trackable listing to clipboard

- gc_little_helper_II.user.js
> Allow Search in logs to be case sensitiv

- gc_little_helper_II.user.js
Ausrichtung Kopf von My Lists und Search und jeweilige Detailanzeige auf neuer Karte
> Prepare v0.14.7

- gc_little_helper_II.user.js
#2433
@capoaira 
Kannst du dir diese Erweiterung bitte mal ansehen? Danke.
> Add link to Komoot on Browse and Search Map

- gc_little_helper_II.user.js
#2424
https://github.com/2Abendsegler/GClh/issues/2424#issuecomment-1793873161
> New Logging Structure, Show Loglength and word count

- gc_little_helper_II.user.js
> New Logging Structure, Show Loglength and word count (2)

- gc_little_helper_II.user.js
>  [Log Form] VIP, VUP, message, mail for owner.

- gc_little_helper_II.user.js
> [Log Form] Show additional cache info.

- gc_little_helper_II.user.js
> [Log Form] Replicate TB-Header to bottom.

- gc_little_helper_II.user.js
> GClh header disappears.

- gc_little_helper_II.user.js
#2424
Neben dem Thema "TB auto visit" habe ich noch eine kleine Änderung beim Thema "Show additional cache info" gemacht, weil mir dort etwas um die Ohren geflogen ist. Die Daten waren schon aufgebaut, sind aber wieder verschwunden. Das kann man aber nur testen, wenn man die Probleme wie im #2443 erzeugen kann, es handelt sich um das gleiche Phänomen. capoaira, du kannst das wohl nicht testen.
> [Log Form] TB auto visit.

- gc_little_helper_II.user.js
> [Log Form] Signatures.

- gc_little_helper_II.user.js
#2424 
wird erst funktionieren, sobald #2435 gemerged ist
~Entfernt auch alte Bookmark Links, die es nicht mehr gib.~
Die Beschreibung im config muss auch noch angepasst werden.
(Ich erstelle die PR nur zur Übersicht)
> F2 for new logging

- gc_little_helper_II.user.js
> [Log Form] Signature disappears on changing the logtype (2)

- gc_little_helper_II.user.js
Uncaught TypeError because of empty log.
#2467
> Clicking on a TB in Latest Activity area causes an Uncaught TypeError.

- gc_little_helper_II.user.js
> [New Dashboard, Log Form] The edit links for the logs in the dashboard should be changed to the new log form.

- gc_little_helper_II.user.js
> fix [Log Form] On the edit log page, GClh is not running

- gc_little_helper_II.user.js
Check fields before use Window.getComputedStyle.
#2474
> [Log Form] Uncaught TypeError: Window.getComputedStyle: Argument 1 is not an object.

- gc_little_helper_II.user.js
close #2482
Link to parameter: https://www.geocaching.com/my/#GClhShowConfig#a#settings_hide_feedback_icon
> Hide survey on Cache Owner Dashboard

- gc_little_helper_II.user.js
> fix signature is insert to tb log

- gc_little_helper_II.user.js
> Hide share botton on log view page

- gc_little_helper_II.user.js
close #2489
Zusätzliche Änderungen:
- Im Bereich "Improve log form" auch die Ermittlung von __NEXT_DATA__ verbessert.
- Im Bereich "Improve log form" auch die Styles nur einmal erzeugen.
- Beschreibung von function addCopyToClipboardLink korrigiert.
Zum Thema "Hide social share button" habe ich nichts geändert, nur eingerückt wegen zusätzlichem try.
> [Log View] Build copy to clipboard icon for logtext.

- gc_little_helper_II.user.js
> Vip, vup, mail message in log form, edit, view for owner and logger

- gc_little_helper_II.user.js
> Default log type must not be set in edit mode.

- gc_little_helper_II.user.js
> [Log Form, Log Edit] Improve checking whether the last changes come from GClh.

- gc_little_helper_II.user.js
> [Log Form, Log Edit, Log View] Do not open links in log automatic in new browser tab.

- gc_little_helper_II.user.js
> [Dashboard] Hide TB-Logs from activity feed

- gc_little_helper_II.user.js
> [Log Form] Enable sorting of TBs by name.

- gc_little_helper_II.user.js
> [Log Form] Default logtypes run into error: can't convert null to object

- gc_little_helper_II.user.js
> [Cache Listing] In the logs the old description "Needs archived" is used instead of "Reviewer attention requested"

- gc_little_helper_II.user.js
Close #2555
Außerdem habe ich folgende Änderung vorgenommen:
`Owner maintenance requested` ersetzt durch `Owner attention requested` beim Setzen des Default log types im Config.
[Edit]
Die Beachtung eines Logtypes in der URL wurde mit 0.15.4 entfernt.
> [Log Form] Default logtype overrides logtype from URL

- gc_little_helper_II.user.js
> [Log Form] Autovisits are not set if log type "Found it" is set by default.

- gc_little_helper_II.user.js
> fix [Friends] Reset button doesn't work

- gc_little_helper_II.user.js
> [Public Profile] For the hide caches in own profile, the finds and not the hides are linked.

- gc_little_helper_II.user.js
> [Log Form] Larger content width and less space between log lines

- data/config_standard.txt
#2565
#2581
Maintain config_standard.txt
> [Log Form] Larger page width and less space between log lines

- gc_little_helper_II.user.js
> [Global] Upgrade button for basic member is not aligned.

- gc_little_helper_II.user.js
> [Cache Listing] Adapt the height of the "personal cache note edit field" doesn't always work.

- gc_little_helper_II.user.js
> [Leaderboard] Hide social sharing via Facebook, X doesn't work.

- gc_little_helper_II.user.js
> Number of bookmark lists in which a cache is contained are no longer displayed with "Add to List(0)".

- data/config_standard.txt
- gc_little_helper_II.user.js
> [Google Maps] Google Maps not being linked from Google Search Results pages.

- gc_little_helper_II.user.js
> [Cache Listing] Listing no longer centered and in intended area.

- gc_little_helper_II.user.js
> [Cache Listing] Add to list and Ignore feature

- gc_little_helper_II.user.js
> [Mail and Message Form] Placeholder for GC-Code without brackets

- gc_little_helper_II.user.js
> [Log Form] Larger page width no longer works.

- gc_little_helper_II.user.js
> [Edit Cache Listing] F2 to save and preview the edited cache listing no longer works.

- gc_little_helper_II.user.js
@capoaira 
Hier gab es gleich zwei Fehler zum Thema. Das Problem mit den Log Types "Owner attention requested" und "Reviewer attention requested" war mir nicht aufgefallen. Super aufgepasst, danke!
In den gelesenen Logs werden teils noch die alten Bezeichnungen verwendet, also "Needs Maintenance" und "Needs Archived". 😕 Das führt hier zum Fehler. Ich habe das nicht elegant gelöst. Ich will aber an dieser Stelle keine großen Anpassungen machen.
close #2620
> [Cache Listing] Select log types in listing not working for some types.

- gc_little_helper_II.user.js
> [Global] Enlarge search field in header so that GC codes are visible.

- gc_little_helper_II.user.js
> [Search Map] Separate "Placed by" and Owner by space in cache details.

- data/config_standard.txt
- gc_little_helper_II.user.js
> [Cache Listing] Show bigger avatar image in cache listing log.

- gc_little_helper_II.user.js
> [Log Form] Log template "Last Cache-Log" inserts old Log instead of last one

- gc_little_helper_II.user.js
> [Log Form] Additional cache info in log form are missing.

- gc_little_helper_II.user.js
> [Search] Alignment of search buttons on filters incorrect.

- gc_little_helper_II.user.js
> [Statistic] Country links to caches you have found do not work.

- gc_little_helper_II.user.js
Cache Listing (Latest Logs und VIP Lists):
Search Map:
> [Cache Listing, Search Map] Improve accessibility of the expanded log details in the Latest Logs and VIP Lists.

- data/config_standard.txt
- gc_little_helper_II.user.js
New button to "Copy Coordinates to Clipboard" for every waypoint.
Settings -> Listing - Additional Waypoints:
---
close #2644
> [Cache Listing] New button to "Copy Coordinates to Clipboard" for every waypoint.

- gc_little_helper_II.user.js
> [Config] settings_listing_ctoc_coords_waypoints mit Version versehen

- gc_little_helper_II.user.js
Old:
New:
---
(Additional: Change description of "Set copy coordinates to clipboard button for Waypoints".)
> [Log Form] Enlarge the date field so that everything is visible also in trackable logs.

- gc_little_helper_II.user.js
> [Log Form] double TB log actions

- data/config_standard.txt
- gc_little_helper_II.user.js
> [Cache Detail] Add event start and end time back to description

- gc_little_helper_II.user.js
> [Log Form] Added placeholder cache type to signature and log templates

- gc_little_helper_II.user.js
> [Cache Listing] The log totals icons at the top are missing and above the logs the log totals icons are displayed incorrectly.

- gc_little_helper_II.user.js
> [Browse Map] The log totals icons are displayed incorrectly in the detailed cache information.

- gc_little_helper_II.user.js
Resizing the finds per month chart doesn't work in all (probably slow) environments. Now it's more robust.
Close #2700
> [Statistic] Fix own scale of graphical monthly founds

- gc_little_helper_II.user.js
- remove initial chart before redrawing the chart
- improve performance of chart draw
> [Statistic] Small improvements for own scale of graphical monthly founds

- gc_little_helper_II.user.js
> fix(Search Map): Set Link to Owner

- gc_little_helper_II.user.js
> [New Dashboard] Links to GClh correctly positioned

- data/main.css
> [New Dashboard] Remove border in menu

- gc_little_helper_II.user.js
> [Cache Listing] Clicking on log type totals at the top of the listing does not work

- gc_little_helper_II.user.js
> [Search Map] Fix showHint - Show hint automatically

- gc_little_helper_II.user.js
#2708
Fix function 'scrollInCacheList' after GS tech migration
> [Search Map] Fix scrollInCacheList - After go back from cache details to cache list or BML, scroll to last position

- data/main.css
> [Config, Sync] Remove bold border of all links when calling from dashboard

- gc_little_helper_II.user.js
> [Search Map] Fix toggleHeader - Hide header

- gc_little_helper_II.user.js
> [Log Form] TB auto visit should not run in edit log mode

- gc_little_helper_II.user.js
#2708
---
- Fix [Search Map] Show additional cache data in cache details  (Tech migration) (function showSearchmapSidebarEnhancements)
- Fix [Search Map] Add VIP, VUP, Mail to owner in cache details  (Tech migration) (function addVipVupMailToOwner)
- Fix [Search Map] F2 keydown in filter screens to apply the settings (Tech migration) (function prepareKeydownF2InFilterScreen)
- Fix [Search Map] Improve add to list pop up (Tech migration) (function improveAddtolistPopup)
---
Additional:
- New [Search Map] Add county (Landkreis) to place in enhanced cache data.
- New [Search Map] Scroll up to top in description after "Description & Hint" was clicked.
- Fix [Browse Map] Number of trackables in cache detail popup only consider 20 trackables.
> [Search Map] Fix (Tech migration)

- gc_little_helper_II.user.js
Fixes [2708#issuecomment-2704763097](https://github.com/2Abendsegler/GClh/issues/2708#issuecomment-2704763097).
> [Search Map] Fix error if default filter and show corrected coords both are active

- gc_little_helper_II.user.js
#2708
- Fix [Search Map, Browse Map] Open latest logs and personal cache note slightly late so it doesn't flutter.
- Fix [Search Map, Browse Map] Put favorite percentage, elevation and place further to the right in the line so that the entire line content is not moved as soon as the data has been determined.
The fixed width components should be output first. Favorite percentage, elevation and county must be determined first. While determining favorite percentage and elevation is usually quite quick, determining the county in particular can sometimes take a while. This later content can then shift parts of the line content to the right, even though you are already viewing the personal cache note, for example.
- Fix [Search Map] Elevation in enhancement block is wrong if cache changed …
> [Search Map, Browse Map] Show additional cache data on the maps.

- gc_little_helper_II.user.js
> [Cache Listing] Filtering logs by clicking on the log type totals no longer works if language is not English

- gc_little_helper_II.user.js
See also #2760 with advanced merge for `init.js` via externals -> master -> collector.
> [Config] Build "on sabbatical" for thanks page

- gc_little_helper_II.user.js
#2708
fix function collapseActivity
> [Search Map] Button to collapse activity (Tech migration)

- gc_little_helper_II.user.js
#2708
`function buildMapControlButtons - initGeoServiceControl`
> [Search Map] Build geoservices map feature (Tech migration)

- gc_little_helper_II.user.js
> [Search Map] Improve buttons above (Tech migration)

- data/main.css
> [New Dashboard] Remove border in GClh header.

- gc_little_helper_II.user.js
> [Recently Viewed Caches] Alternate color for lines overwrite user owned color.

- gc_little_helper_II.user.js
In Linux (FF and Chrome), the code for getting a handle to the search map object runs too early and therefore triggers an error.
In Windows this is not an issue.
Now the code execution is safely delayed until the necessary global variables are available.
> [Search Map] Fix map handle error in Linux

- data/config_standard.txt
- gc_little_helper_II.user.js
> [Cache Listing] Show favorite points in logs.

- gc_little_helper_II.user.js
> [Souvenirs] Display "Sort by" selection in full width.

- gc_little_helper_II.user.js
> [Statistic] Make countries and states clickable on other users statistic maps.

- gc_little_helper_II.user.js
As discussed, support for setting default filters is withdrawn.
Reasons (just for the record):
When calling the search map page, all cache results are already embedded inside the page, no further requests for caches will be done.
In order to apply gclh default filters, there are two options:
1. adapt the embedded results as early as possible, i.e. before further processing starts
- gclh needs to start as early as possible, which requires to change to `@run-at document-start`
- this has the potential to break other functionality, even unnoticed
- trying to solve this leads to complex and hard to maintain code parts
2. apply the default filters during page load to the filter dialog and perform a filtered search as soon as possible
- also leads to complex code parts
- multiple dependencies …
> [Search Map] Withdraw support for setting default filters

- data/config_standard.txt
- gc_little_helper_II.user.js
Additional:
Improve look of own Map and Search button in left sidebar.
> [New Dashboard] Renew and improve compact layout.

- data/config_standard.txt
- gc_little_helper_II.user.js
> [New Dashboard] Hide individual rows in the navigation column of your dashboard.

- data/config_standard.txt
- gc_little_helper_II.user.js
> [New Dashboard] Build new link "Search Map" in the navigation column of the new dashboard.

- data/init.js
- data/main.css
> [Cache Listing] Add custom links to right navigation sidebar (advanced merge).

- gc_little_helper_II.user.js
Minimale Implementierung für Issue #2825 
Funktioniert aktuell im Listing Header. Evtl. ist es sinnvoll dies auch für die Logs o.ä. zu erweitern.
> [Cache Listing] Adding GC Code to message owner / user link

- gc_little_helper_II.user.js
Uncaught TypeError: map is null
> [Trackable Map] Resizing and zooming with the mouse wheel no longer works.

- gc_little_helper_II.user.js
> [Search Map] Link to search map is changed

- gc_little_helper_II.user.js
> [New Dashboard] Use the correct icon for the browse map link.

- gc_little_helper_II.user.js
> [Cache Listing, Message Form] Adding GC Code to message link

- gc_little_helper_II.user.js
> [Log Form] Uncaught TypeError in function waitForTbsHide.

- gc_little_helper_II.user.js
The reason for the missing autovisit buttons was not the language, but a missing "Hide TBs" processing for newly displayed trackables after "Show all".
Additional: 
The TB header may only be duplicated downwards once all trackables are present and the correct buttons are present. The same applies to the "Sort by name" button.
close #2863
> [Log Form] Autovisit buttons are missing sometimes if more than 20 TBs.

- gc_little_helper_II.user.js
> [Browse Map] JSON.parse error in geonames elevation data no longer displays as an error.

- gc_little_helper_II.user.js
> [Log Trackable] Overflow trackable log form on the right side.
